- name: Repmgr | Detect primary
  shell: "set -o pipefail ; {{ postgresql_bin_directory }}/repmgr -f {{ repmgr_config_directory }}/repmgr.conf cluster show | grep primary | cut -d '|' -f 2"
  register: repmgr_primary_check
  become: yes
  become_user: postgres
  ignore_errors: True

- name: Repmgr | Declare as primary for existing installation
  set_fact:
    repmgr_primary: "{{ True if ansible_hostname == repmgr_primary_check.stdout.strip() else False }}"
  register: repmgr_existing_installation_detected
  when: "repmgr_primary_check.stdout is defined and repmgr_primary_check.rc == 0"

- name: Repmgr | Declare as primary for new installation
  set_fact:
    repmgr_primary: "{{ True if ansible_hostname == repmgr_master or inventory_hostname == repmgr_master else False }}"
  when: "repmgr_existing_installation_detected is skipped"

- debug:
    var: repmgr_primary

- debug:
    var: repmgr_master

- debug:
    var: ansible_hostname
